name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: "GitHub Release 标签，例如 custom-1.5.0"
        required: true
        default: "custom-1.5.0"
        type: string
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
